---
title: "Lab-04"
author: "Negar"
date: "2/10/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
```


```{r loading data}
dictionary <- readr::read_csv(here::here("data", "green_dictionary.csv"))
green_data <- readr::read_csv(here::here("data", "green_data.csv"))
```

## Question 1

```{r}
dictionary |>
  summarize(dictionary)
green_data_changed <- green_data |>
                na_if("-99")
reversed <- dictionary |>
  filter(Keying == -1) |>
  pull(Item)
green_data_reverse <- green_data_changed |> 
  mutate(across(all_of(reversed),
                ~ recode(.x, "1"= 5, "2" = 4, "3" = 3, "4" = 2, "5" = 1),
                .names = "{.col}r"))
green_data_changed$student <- recode_factor(green_data_changed$student, '1' = "Non-student", '2' = "Student", .default = NULL)
```

## Question 2

```{r}
green_data_changed |>
  rowwise() |> 
  mutate(
    Green_total = mean(c_across(green1:green5), na.rm = TRUE),
    Comp_total = mean(c_across(comp1:comp10), na.rm = TRUE),
    Intel_total = mean(c_across(intel1:intel10), na.rm = TRUE),
    Open_total = mean(c_across(open1:open10), na.rm = TRUE)
  ) |>
  ungroup()
```

## Question 3

```{r}
green_data_pomp <- green_data_changed |> 
  mutate(across(c(green1:open10),
         ~ recode(.x, "1"= 0,"2" = 25, "3" = 50, "4" = 75,"5"= 100),
                .names = "{.col}_pomp"))
print(green_data_pomp)
```

## Question 4

```{r}
Avg_green_data_pomp <- green_data_pomp |>
  rowwise() |> 
  mutate(Green_pomp = mean(c_across(green1:green5), na.rm = TRUE),
         Comp_pomp = mean(c_across(comp1:comp10), na.rm = TRUE),
         Intel_pomp = mean(c_across(intel1:intel10), na.rm = TRUE),
         Open_pomp = mean(c_across(open1:open10), na.rm = TRUE))
Avg_green_data_pomp$student <- recode_factor(Avg_green_data_pomp$student, '1' = "Non-student", '2' = "Student", .default = NULL)

Avg_green_data_pomp |>
ggplot() +
aes(x = Green_pomp) +
  geom_histogram(fill = "darkgreen") +
  geom_density(fill="black") +
  ylab("Count")

Avg_green_data_pomp |> 
ggplot() +
aes(x = Comp_pomp) +
  geom_histogram(fill = "purple") +
  geom_density(fill="black") +
  ylab("Count")

Avg_green_data_pomp |>
ggplot() +
aes(x = Intel_pomp) +
  geom_histogram(fill = "darkblue") +
  geom_density(fill="black") +
  ylab("Count")

Avg_green_data_pomp |> 
ggplot() +
aes(x = Open_pomp) +
  geom_histogram(fill = "darkred") +
  geom_density(fill="black") +
  ylab("Count")
```

## Question 5

```{r}
Avg_green_data_pomp |> 
  filter(!is.na(student)) |> 
  ggplot() +
  aes(x = Green_pomp, y = Comp_pomp,
      group = student,
      color = student,
      fill = student) + 
  geom_point(alpha = .5) +
  geom_smooth(method = "lm")
  
Avg_green_data_pomp |> 
  filter(!is.na(student)) |> 
  ggplot() +
  aes(x = Green_pomp, y = Intel_pomp,
      group = student,
      color = student,
      fill = student) + 
  geom_point(alpha = .5) +
  geom_smooth(method = "lm")

Avg_green_data_pomp |> 
  filter(!is.na(student)) |> 
  ggplot() +
  aes(x = Green_pomp, y = Open_pomp,
      group = student,
      color = student,
      fill = student) + 
  geom_point(alpha = .5) +
  geom_smooth(method = "lm")
```

In all three plots, the non-student group showed higher scores at first, and then the scores for the student group went higher than the non-student group.

## Question 6

```{r}
ggplot(na.omit(Avg_green_data_pomp)) +
  geom_jitter(aes(x = Green_pomp, y = student,
      fill = student,
      color = student), height = .15) +
  geom_point(aes(x = Green_pomp, y = student,
      fill = student,
      color = student)) +
  geom_bar(aes(x = Green_pomp,
      fill = student,
      color = student), alpha = 0.5) +
  geom_density(aes(x = Green_pomp,
      fill = student,
      color = student), alpha = 0.5)
```

Overall, non-student group had higher environmental awareness scores compared to student group.

## Question 7

```{r}
table <- Avg_green_data_pomp |>
  na.omit() |>
  group_by(student) |>
  summarize(across(c(Green_pomp, Comp_pomp, Intel_pomp, Open_pomp),
            list(
              Mean = ~ mean(.x, na.rm = T),
              SDs = ~ sd(.x, na.rm = T),
              Medians = ~ median(.x, na.rm = T),
              Minima = ~ min(.x, na.rm = T),
              Maxima = ~ max(.x, na.rm = T)
            )))
table
```

